<h1>Questions-Réponses</h1>

<div class="Section">
<h1>Comment installer le certificat ?</h1>
<div class="TwoColumns">
<div class="Left">
<p>
Pour accéder à votre espace client, vous avez reçu un certificat. La documention suivante décrit la procédure
à suivre pour installer le certificat sur votre navigateur Web.
</p>
</div>
<div class="Right">
<a rel="nofollow" target="_blank" href="<?php echo $LINKS["DocCertificat"]; ?>"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>

<div id="BottomMenu">
Copyright 2007 BlueEyeVideo Tous droits réservés
</div>
