<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
 <title>
 <?php myhtmlentities(_("Welcome to BluePortail")) ?>
 </title>
 <meta http-equiv="content-type" content="text/html; charset=utf-8" ></meta>
<meta name="verify-v1" content="D5pyRkGAMEyLpG6QyXbiGIh35wfOXeoeV9nQ4tj6LPA=" ></meta>
 <link rel="stylesheet" type="text/css" href="<?php echo BLUEPHPROOT . "/BluePHP/css/blueportail/screen.css"; ?>"></link>
 <link rel="shortcut icon" href="/BlueSystem/styles/favicon.ico" type="image/vnd.microsoft.icon"></link>
 <link rel="icon" href="/BlueSystem/styles/favicon.ico" type="image/vnd.microsoft.icon"></link>
<?php echo $headerExt; ?>
</head>
<body>
