<style type="text/css" media="screen">

img#BTopBoxImage {
  margin-top: 20px;
  margin-bottom: 20px;
  margin-left: 175px;
  margin-right: 175px;
  width: 600px;
  border: solid 2px #0b58c2;
}

</style>

<img id="BTopBoxImage" src="styles/BTopBoxImage.jpeg"></img>

<div class="Section">
<h1>Nos offres</h1>
<div class="TwoColumns">
<div class="Left">
<p>
Découvrez nos offres autour des solutions de comptage sur notre sîte Web.
</p>
</div>
<div class="Right">
<a href="<?php echo $LINKS['BlueEyeVideo']; ?>"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>

<div class="Section">
<h1>Espace client</h1>
<div class="TwoColumns">
<div class="Left">
<p>
Vous avez souscrit à l'offre B-Top Box. Découvrez l'espace client pour accéder notamment aux statistiques 
de comptage.
</p>
</div>
<div class="Right">
<a href="<?php echo $LINKS['BluePortail']; ?>"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>

<div id="BottomMenu">
Copyright 2007 BlueEyeVideo Tous droits réservés
</div>

