<h1>Contact us</h1>
<p>
</p>

<!--
<div class="Section">
<h1>Informations pratiques</h1>
<div class="TwoColumns">
<div class="Left">
<p>
Si vous avez des problèmes pour utiliser nos services, consultez notre section Questions-Réponses en cliquant sur
le bouton ci-contre.
</p>
</div>
<div class="Right">
<a href="index.php?page=faq"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>
-->
<div class="Section">
<h1>By e-mail</h1>
<p>
Our technical service is available via the following e-mail adress  :
<ul>
<li>support@blueeyevideo.com</li>
</ul>
</p>
</div>

<!--
<div class="Section">
<h1>Par téléphone</h1>
<p>
Notre service technique est accessible par téléphone au :
<ul>
<li>+00 33 (0)4 56 14 10 70</li>
</ul>
</p>
</div>
-->
<div id="BottomMenu">
Copyright 2007 BlueEyeVideo All right reserved
</div>
