<h1>Nous contacter</h1>
<p>
</p>

<div class="Section">
<h1>Informations pratiques</h1>
<div class="TwoColumns">
<div class="Left">
<p>
Si vous avez des problèmes pour utiliser nos services, consultez notre section Questions-Réponses en cliquant sur
le bouton ci-contre.
</p>
</div>
<div class="Right">
<a href="index.php?page=faq"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>

<div class="Section">
<h1>Par e-mail</h1>
<p>
Notre service technique est accessible à l'adresse e-mail suivante :
<ul>
<li>support@blueeyevideo.com</li>
</ul>
</p>
</div>

<div class="Section">
<h1>Par téléphone</h1>
<p>
Notre service technique est accessible par téléphone au :
<ul>
<li>+00 33 (0)9 81 99 38 04</li>
</ul>
</p>
</div>

<div id="BottomMenu">
Copyright 2012 BlueEyeVideo Tous droits réservés
</div>
