<h1>FAQ</h1>
<p>
Sorry, this section is currently available only in french.
</p>

<div class="Section">
<h1>Comment désactiver la boite de dialogue "Cette page contient des éléments sécurisés et non sécurisés" ?</h1>
<p>
Sous Microsoft Internet Explorer, une boite de dialogue peut apparaître à l'affichage de certaines pages. Elle contient les deux phrases suivantes : 
<pre>
Cette page contient des éléments sécurisés et non sécurisés.
Souhaitez-vous afficher les éléments non sécurisés ?
</pre>
Elle apparait sur les sites sécurisés contenant un contenu mixte.
Pour désactiver cette boite de dialogue sous Internet Explorer 6,
<ul>
<li>allez dans "Options Internet",</li>
<li>choisir l'onglet "Sécurité",</li>
<li>sélectionnez la zone "Internet", </li>
<li>cliquez ensuite sur "Personnaliser ce niveau",</li>
<li>dans la section "Divers", cochez le bouton radio "Activé" pour l'élément "Afficher un contenu mixte".</li>
</ul>
</p>
</div>

<div class="Section">
<h1>Pourquoi les graphiques ne s'affichent pas ?</h1>
<p>
L'affichage des graphiques nécessite la présence du module <b>Adobe Flash Player</b> dans votre navigateur. 
Celui-ci est disponible sur le site d'<a rel="nofollow" target="_blank" href="http://www.adobe.fr">Adobe</a>.
Veuillez consulter votre responsable informatique pour de plus amples informations.
</p>
</div>

<div class="Section">
<h1>Quels sont les navigateurs Webs compatibles ?</h1>
<p>
Nous avons testé nos pages Webs sur les navigateurs suivants :
<ul>
<li>Firefox version 2.0</li>
<li>Microsoft Internet Explorer 6.0</li>
<li>Opera 9.25</li>
<li>Konqueror 3.5.4</li>
</ul>
</p>
</div>

<div class="Section">
<h1>Comment récupérer les données sous MS Excel ?</h1>
<div class="TwoColumns">
<div class="Left">
<p>
Consultez la partie tutoriaux de la documention du BlueCount Manager en cliquant sur le bouton ci-contre.
</p>
</div>
<div class="Right">
<a href="/Docs/BlueCountManager_fr_FR.pdf"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>

<div id="BottomMenu">
Copyright 2007 BlueEyeVideo Tous droits réservés
</div>
