<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "<?php echo $isHTTPS ? "https://" : "http://"; ?>www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="<?php echo $isHTTPS ? "https://" : "http://"; ?>www.w3.org/1999/xhtml" xml:lang="en">
<head>
<title><?php echo $title; ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="Keywords" content="Blue Eye Video, Blue Count" />
<meta http-equiv="Description" content="Blue Count HTML Interface."/>
<link rev="made" href="mailto:fabien.pelisson@blueeyevideo.com" />
<link rel="stylesheet" type="text/css" href="<?php echo BLUEPHPROOT . "/BluePHP/css/blueportail/screen.css"; ?>"></link>
<link rel="shortcut icon" href="/BlueSystem/styles/favicon.ico" type="image/vnd.microsoft.icon" />
<link rel="icon" href="/BlueSystem/styles/favicon.ico" type="image/vnd.microsoft.icon" />
<?php echo $headerExt; ?>
</head>
<body>
