<h1>Bienvenue sur le Portail Web de BlueEyeVideo</h1>
<p>
Ce portail a été créé pour vous permettre d'accéder aux données statistiques de vos
compteurs ainsi qu'aux différents services qui seront prochainement disponibles.
</p>

<div class="Section">
<h1>Informations personnelles</h1>
<p>
Votre identifiant client est : <b><?php echo $clientBluePortail ?></b>
</p>
</div>

<div class="Section">
<h1>Accéder aux statistiques</h1>
<div class="TwoColumns">
<div class="Left">
<p>
Pour accéder aux données statistiques de comptage de votre ou vos magasins, cliquez sur l'icône ci-contre.
Si vous souhaitez accéder directement aux statistiques sans passer par le Portail, ajoutez l'addresse du serveur
de statistique dans votre Marque-Pages.
</p>
</div>
<div class="Right">
<a rel="nofollow" target="_blank" href="/BlueCountGUI/index.php"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>

<!--
<div class="Section">
<h1>Accéder à la démonstration en ligne du BlueMarketTrack</h1>
<div class="TwoColumns">
<div class="Left">
<p>
Pour accéder au démonstrateur de l'interface graphique du BlueMarketTrack, cliquez sur l'icône ci-contre.
</p>
</div>

<div class="Right">
<a rel="nofollow" target="_blank" href="/BlueMarketTrackGUI/index.php"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>
-->

<div class="Section">
<h1>Informations pratiques</h1>
<div class="TwoColumns">
<div class="Left">
<p>
Si vous avez des problèmes pour utiliser nos services, consultez notre section Questions-Réponses en cliquant sur
le bouton ci-contre.
</p>
</div>
<div class="Right">
<a href="index.php?page=faq"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>

<div id="BottomMenu">
Copyright 2008 BlueEyeVideo Tous droits réservés
</div>
