<h1>Welcome on the BlueEyeVideo web portal</h1>
<p>
This portal has been created to enable you to access the statistical data of your counters.
</p>

<div class="Section">
<h1>Personal Data</h1>
<p>
Your client reference is : <b><?php echo $clientBluePortail ?></b>
</p>
</div>

<div class="Section">
<h1>Access to the statistics</h1>
<div class="TwoColumns">
<div class="Left">
<p>
To access to the statistical counting data of your shop(s), click on the opposite icon.
If you want to access directly to the statistics without going through the portal, add the adress of statistics page to your bookmark.
</p>
</div>
<div class="Right">
<a rel="nofollow" target="_blank" href="/BlueCountGUI/index.php"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>

<div class="Section">
<h1>Access to the BlueMarketTrack demonstrator</h1>
<div class="TwoColumns">
<div class="Left">
<p>
To access to the demonstrator of the GUI of BlueMarketTrack, click on the opposite icon.
</p>
</div>
<div class="Right">
<a rel="nofollow" target="_blank" href="/BlueMarketTrackGUI/index.php"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>

<!--
<div class="Section">
<h1>Informations pratiques</h1>
<div class="TwoColumns">
<div class="Left">
<p>
Si vous avez des problèmes pour utiliser nos services, consultez notre section Questions-Réponses en cliquant sur
le bouton ci-contre.
</p>
</div>
<div class="Right">
<a href="index.php?page=faq"><img src="styles/gobouton.jpeg"></img></a>
</div>
</div>
</div>
-->

<div id="BottomMenu">
Copyright 2008 BlueEyeVideo Tous droits réservés
</div>
